# Generated by Django 5.2.1 on 2025-09-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blogpost_image_comment_created_at_skill_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
