# Generated by Django 5.2.1 on 2026-02-08 19:17

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcoverimage',
            name='project',
        ),
        migrations.CreateModel(
            name='LeetCodeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_number', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('problem_statement', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Problem Statement')),
                ('approach', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Approach / Thought Process')),
                ('solution_code', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Solution Code')),
                ('explanation', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Code Explanation')),
                ('time_complexity', models.CharField(max_length=50)),
                ('space_complexity', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=10)),
                ('leetcode_url', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogCoverImage',
        ),
        migrations.DeleteModel(
            name='ProjectCoverImage',
        ),
    ]
